Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,15 +14,17 @@ jobs:
 
       - name: Simulate a build
         id: build-step
-        continue-on-error: true
         run: |
-          curl hhs
-          exit 0 # Replace with your actual build commands
+          # Replace with your actual build commands
+          echo "Running build commands..."
+          # Example: ./build.sh
+          # Intentional failure for testing
+          # exit 1
+          exit 0
 
       - name: Push build status to Pushgateway
         if: always()
         run: |
-          sudo apt-get update && sudo apt-get install -y curl
           if [ "${{ job.status }}" = "success" ]; then
             STATUS=1
           else
